"""Closed vocabulary for the durable e-CF delivery timeline."""

OUTBOX_PREPARED = "OUTBOX_PREPARED"
POST_STARTED = "POST_STARTED"
POST_RECEIVED = "POST_RECEIVED"
REMOTE_STATUS = "REMOTE_STATUS"
REMOTE_NOT_FOUND = "REMOTE_NOT_FOUND"
REMOTE_ABSENCE_CONFIRMED = "REMOTE_ABSENCE_CONFIRMED"
RECONCILED = "RECONCILED"
BLOCKED_STATUS_NOT_FOUND = "BLOCKED_STATUS_NOT_FOUND"
STALE_SUBMISSION = "STALE_SUBMISSION"
DELIVERY_FAILED = "DELIVERY_FAILED"
OPERATIONAL_ALERT = "OPERATIONAL_ALERT"
ALERT_DELIVERED = "ALERT_DELIVERED"
ALERT_FAILED = "ALERT_FAILED"
RECOVERED = "RECOVERED"
MANUAL_RETRY = "MANUAL_RETRY"
BACKFILL = "BACKFILL"

EVENT_TYPES = (
    OUTBOX_PREPARED,
    POST_STARTED,
    POST_RECEIVED,
    REMOTE_STATUS,
    REMOTE_NOT_FOUND,
    REMOTE_ABSENCE_CONFIRMED,
    RECONCILED,
    BLOCKED_STATUS_NOT_FOUND,
    STALE_SUBMISSION,
    DELIVERY_FAILED,
    OPERATIONAL_ALERT,
    ALERT_DELIVERED,
    ALERT_FAILED,
    RECOVERED,
    MANUAL_RETRY,
    BACKFILL,
)


def validate_event_type(event_type: str) -> str:
    if event_type not in EVENT_TYPES:
        raise ValueError(f"Unsupported ECF delivery event type: {event_type}")
    return event_type
